def get_video_links_for_mistakes(mistakes: list[str]) -> list[str]:
    video_links = {
        "a": "https://www.youtube.com/watch?v=AG3Lo4_LrB4",
        "b": "https://www.youtube.com/watch?v=ZW43f_nKw8o",
        "c": "https://www.youtube.com/watch?v=xcQwtlPJmp4",
        "ç": "https://www.youtube.com/watch?v=MOVBmHY5R_I",
        "d": "https://www.youtube.com/watch?v=Sh_LnUC0d5A",
        "e": "https://www.youtube.com/watch?v=VjUlE-FAHkM",
        "f": "https://youtu.be/i7tObWJmFoA?si=lgGN9FGVb1vAnEPa",
        "g": "https://youtu.be/HDLMdrE7YC4?si=jsE9CFDTm6LyhQoV",
        "ğ": "https://youtu.be/ClnsoZ1gODQ?si=za5fWF5jyVmTP5t4",
        "h": "https://youtu.be/0PF8I-WHvF4?si=xkSx_Yq4sQt5yWJp",
        "ı": "https://youtu.be/KvaFp_-9ElM?si=2fJ2Lp2hmss-XsCH",
        "i": "https://youtu.be/2OLO9fe4f98?si=ARlAqUNAAuLzaBJS",
        "j": "https://youtu.be/M7qtFmpi6Pc?si=R-D_FBeTufDdRDCY",
        "k": "https://youtu.be/74jJxMn9p9s?si=OVZDGtAGsaegvD5X",
        "l": "https://youtu.be/UwLkKsorhCc?si=YdSChIGNJ48QfZ7z",
        "m": "https://youtu.be/3xql5A02x3E?si=rPMI5__mEeZl3239",
        "n": "https://youtu.be/S23KNX_Jd7A?si=SXd2b1EFIU1MuzMA",
        "o": "https://www.youtube.com/watch?v=uaCE8sZna6g",
        "ö": "https://www.youtube.com/watch?v=5hojSne7OLk",
        "p": "https://youtu.be/f5v-Ui8uclQ?si=lm3NJ4HpOCO--rZw",
        "r": "https://youtu.be/SoxMRXR2GGg?si=reAFkBYybXGjW7Z-",
        "s": "https://youtu.be/MWM44tSVvxA?si=EdcAmXkzzlyFd7nq",
        "ş": "https://youtu.be/v_ndaoq6Rss?si=2kHJTm60r2ei7JVQ",
        "t": "https://youtu.be/Ss58XwYawVM?si=qrLWil7ZyMuEmVH9",
        "u": "https://youtu.be/3GZJVAYJJYI?si=DCdx28DclWCS6bPa",
        "ü": "https://youtu.be/2I9kzUWQi2c?si=q4pINiQOVl4h7sdW",
        "v": "https://youtu.be/1gyrCbQQ6q4?si=sNkeSHJivUKTxNRs",
        "y": "https://youtu.be/RcLMR4XszA8?si=Vh938R7a0jUEyJuh",
        "z": "https://youtu.be/0whQOrIzv-k?si=THe_NuifcchfImYz",
        "0": "https://youtu.be/tuTZZfPb9ek?si=FC1pHeZ5UTcsbsUQ",
        "1": "https://youtu.be/abiSK2YKSTE?si=mUIKUKClGHixgm0H",
        "2": "https://youtu.be/1bDgmGSa2jc?si=7Is9Ga30mSwL3pja",
        "3": "https://youtu.be/Fdt_TUG_SRs?si=N3aBLqCuwfIS4OTt",
        "4": "https://youtu.be/4zN5iS2894Q?si=D7wi8NEXSNj_d-jS",
        "5": "https://youtu.be/awsYYUcoutY?si=6pYHsPHp0NzruGi8",
        "6": "https://youtu.be/w8sdx-nQ7T4?si=fSn75XUWyOgyAZ2t",
        "7": "https://youtu.be/m-OTpUZVoXE?si=k2j6G-j6Gy7OHSXw",
        "8": "https://youtu.be/TyO2IfG5_Ts?si=ux02o3J9TYWe8EM5",
        "9": "https://youtu.be/9ZLWYN-srHg?si=65SlApJ10swZkZnM",
    }

    unique_mistakes = set(mistakes)

    return [video_links[char] for char in unique_mistakes if char in video_links]